### ISSUE TITLE
The api is no longer returning upcoming matches, all matches api is returning right now are already finished. Please update

### ISSUE THREAD

**Issue by nasyx-rakeeb** [raminmr/free-api-worldcup2022#137]

**Comment by rezarahiminia** [comment]
fixed

**Comment by nasyx-rakeeb** [comment]
Why did you close the issue, its not fixed yet, its only returning 3 matches that have a value of `FALSE `for `Finished` property and there's literally nothing in these matches, all fields are *empty* except `id`
