### ISSUE TITLE
 http://api.cup2022.ir/api/v1/match return wrong match time and date 

### ISSUE THREAD

**Issue by djdmg** [raminmr/free-api-worldcup2022#20]
First at all, a big thaks for your work. 
Some date and time seem to be wrong:
For example: Qatar VS Equator is on: 2022-11-21 19:00:00 instead of 2022-11-20 19:00:00 

Cheers
Dim

**Comment by raminmr** [comment]
thank you for report
Was corrected

**Comment by kavish-agarwal** [comment]
@raminmr  I am still getting "local_date": "11/21/2022 19:00"
